management.endpoints.web.exposure.include=*
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:6541/ewm-main
spring.datasource.username=main
spring.datasource.password=main
spring.sql.init.mode=always