CREATE TABLE users (
    user_id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE events (
    event_id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    annotation TEXT,
    description TEXT,
    category_id BIGINT NOT NULL REFERENCES categories(category_id),
    initiator_id BIGINT NOT NULL REFERENCES users(user_id),
    event_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    paid BOOLEAN DEFAULT FALSE,
    participant_limit INT DEFAULT 0,
    state VARCHAR(50) DEFAULT 'PENDING',
    views INT DEFAULT 0
);

-- CREATE TABLE event_requests (
--     request_id BIGSERIAL PRIMARY KEY,
--     event_id BIGINT NOT NULL REFERENCES events(event_id),
--     requester_id BIGINT NOT NULL REFERENCES users(user_id),
--     status VARCHAR(50) DEFAULT 'PENDING',
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );

CREATE TABLE participation_requests (
                                        id BIGSERIAL PRIMARY KEY,
                                        event_id BIGINT NOT NULL REFERENCES events(event_id),
                                        requester_id BIGINT NOT NULL REFERENCES users(user_id),
                                        status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
                                        created TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                        CONSTRAINT uq_event_requester UNIQUE (event_id, requester_id)
);

CREATE INDEX idx_pr_event ON participation_requests (event_id);
CREATE INDEX idx_pr_requester ON participation_requests (requester_id);


CREATE TABLE compilations (
    compilation_id BIGSERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
);

-- Link events to compilations
CREATE TABLE compilation_events (
    compilation_id BIGINT NOT NULL REFERENCES compilations(compilation_id),
    event_id BIGINT NOT NULL REFERENCES events(event_id),
    PRIMARY KEY (compilation_id, event_id)
);

-- CREATE TABLE IF NOT EXISTS events (
--     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--     initiator_id BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
--     category_id BIGINT NOT NULL REFERENCES categories ON DELETE CASCADE,
--     annotation VARCHAR(2000) NOT NULL,
--     description VARCHAR(7000) NOT NULL,
--     title VARCHAR(120) NOT NULL,
--     lat REAL NOT NULL,
--     lon REAL NOT NULL,
--     paid BOOLEAN NOT NULL,
--     participantLimit INTEGER NOT NULL,
--     requestModeration BOOLEAN NOT NULL,
--     eventDate TIMESTAMP NOT NULL,
--     createdOn TIMESTAMP NOT NULL,
--     publishedOn TIMESTAMP NOT NULL,
--     state VARCHAR(20) NOT NULL,
--     CONSTRAINT pk_event PRIMARY KEY (id)
-- )