services:
  postgres:
    image: postgres:16
    container_name: postgres-ewm
    restart: unless-stopped
    ports:
      - "5432:5434"
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
    volumes:
      - pg_ewm_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U main -d ewm"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pg_ewm_data:
